"""
Senior title taxonomy - the 533-title master list from Ian, grouped
into 9 categories.

Matching rules:
    - Case-insensitive.
    - Longest-title-first (so 'Director of Research Development' wins
      over 'Director of Research').
    - Categories checked in priority order (see CATEGORY_ORDER) so a
      person whose title fits two categories is bucketed to the more
      senior one.
    - After exact-phrase matching, a small set of keyword fallbacks
      catches British/American spelling variants and hyphen variants.
"""
import re

CATEGORY_ORDER = [
    "Senior Executive",              # Cat 2 - PVCs, VPs Research etc.
    "Research Leadership",           # Cat 1
    "Research Contracts & Compliance",   # Cat 7
    "Research Finance & Accounting",     # Cat 8
    "Sponsored / Grants / Awards",       # Cat 3 + 4 + 5 + 6 (all grant-shop roles)
    "Research Systems & Digital",        # Cat 9
    "Secondary",                     # Cat 10 - VC, CFO, CIO etc. review-only
]


SENIOR_TITLES = {
    "Senior Executive": [
        # From "Senior Research Executives and Global Equivalents"
        "Pro-Vice-Chancellor (Research)",
        "Pro-Vice-Chancellor (Research and Innovation)",
        "Pro-Vice-Chancellor (Research and Knowledge Exchange)",
        "Pro Vice-Chancellor for Research",
        "Pro Vice-Chancellor for Research and Innovation",
        "Vice-Principal (Research)",
        "Vice-Principal (Research and Innovation)",
        "Vice-Principal (Research and Knowledge Exchange)",
        "Deputy Vice-Chancellor (Research)",
        "Deputy Vice-Chancellor (Research and Innovation)",
        "Deputy Vice-Chancellor (Research and Enterprise)",
        "Vice President for Research",
        "Vice President for Research and Innovation",
        "Vice President for Research and Economic Development",
        "Vice President for Research and Knowledge Transfer",
        "Vice Chancellor for Research",
        "Vice Chancellor for Research and Innovation",
        "Senior Vice Chancellor for Research",
        "Senior Vice Chancellor for Research and Innovation",
        "Vice Provost for Research",
        "Vice Provost for Research and Innovation",
        "Vice Provost and Dean of Research",
        "Associate Vice Provost for Research",
        "Associate Vice Provost for Research Administration",
        "Dean for Research",
        "Dean of Research",
        "Associate Dean for Research",
        "Deputy Dean for Research",
        "Vice-Rector for Research",
        "Vice-Rector for Research and Innovation",
        "Vice-President (Research and Innovation)",
        "Senior Vice President (Research and Innovation)",
        "Deputy President (Research and Technology)",
        "Deputy President (Research and Innovation)",
        "Executive Vice President for Research",
        "Chief Research Officer",
        "Senior Associate Vice President for Research",
        "Pro-Warden for Research Enterprise and Knowledge Exchange",
        "Provost and Deputy Vice-Chancellor for Research and Knowledge Exchange",
        "Vice-President Research and Innovation",
        "Vice-President Research and Strategic Initiatives",
        "Vice-President Research",
        "Vice President (Research)",
        "Deputy Vice-Chancellor Research and Innovation",
        "Deputy Vice-Chancellor Research",
        "Vice-Rector of Faculty and Research",
        "Interim Vice Provost for Research Development",
        "Associate Vice President for Research Administration",
        "Assistant Vice President for Research",
        "Assistant Vice President for Research Administration",
        "Associate Vice President for Research Development",
        "Assistant Vice Provost for Research",
        "Vice Provost for Research and Creative Activity",
        "Chief Research Administration Officer",
        "Senior Dean for Research and Scholarship",
        "Assistant Dean for Research",
        "Assistant Dean for Research Administration",
        "Assistant Dean for Research Operations",
    ],
    "Research Leadership": [
        "Executive Director of Research Services",
        "Senior Director of Research Services",
        "Director of Research Services",
        "Associate Director of Research Services",
        "Deputy Director of Research Services",
        "Head of Research Services",
        "Executive Director of Research Administration",
        "Associate Director of Research Administration",
        "Deputy Director of Research Administration",
        "Director of Research Administration",
        "Head of Research Administration",
        "Director of Research Support and Governance",
        "Head of Research Support and Governance",
        "Director of Research Support",
        "Head of Research Support",
        "Director of Research Office",
        "Head of Research Office",
        "Research Office Director",
        "Director of Research Operations",
        "Head of Research Operations",
        "Research Operations Director",
        "Director of Research and Innovation Services",
        "Director of Research and Enterprise Services",
        "Director of Research and Knowledge Exchange Services",
        "Head of Research and Innovation Services",
        "Head of Research and Enterprise Services",
        "Head of Research and Knowledge Exchange Services",
        "Director of Research and Innovation",
        "Head of Research and Innovation",
        "Director of Research and Enterprise",
        "Head of Research and Enterprise",
        "Director of Research and Knowledge Exchange",
        "Head of Research and Knowledge Exchange",
        "Director of Research Innovation and Knowledge Exchange",
        "Director of Research Innovation and Impact",
        "Director of Research and Impact",
        "Director of Research and Innovation Office",
        "Director of Research Engagement and Innovation Office",
        "Director of Research Strategy",
        "Head of Research Strategy",
        "Research Strategy Director",
        "Deputy Director of Research and Enterprise",
        "Executive Director Research and Innovation Services",
        "Director of Research and Sponsored Programs",
        "Senior Director of Research and Sponsored Programs",
        "Director of Research Scholarship and Sponsored Programs",
        "Director of the Office of Research and Sponsored Programs",
        "Director of Office of Research Management",
        "Executive Director of Office of Research Management",
        "Head of the Research Support Office",
        "Director of Research Accounts",
        "Executive Director for Research Administration",
        "Research Administration Director",
        "Director of Sponsored Research and Programs",
        "Director of Research Administration Operations",
        "Director of Research",
        "Head of Research",
    ],
    "Research Contracts & Compliance": [
        "Director of Research Contracts",
        "Head of Research Contracts",
        "Research Contracts Director",
        "Senior Research Contracts Manager",
        "Research Contracts Manager",
        "Research Contracts Officer",
        "Commercial Research Contracts Manager",
        "Contracts and Grants Director",
        "Director of Contracts and Grants",
        "Head of Contracts and Grants",
        "Grants and Contracts Manager",
        "Grant and Contract Officer",
        "Research Agreements Manager",
        "Research Agreements Officer",
        "Director of Research Compliance",
        "Head of Research Compliance",
        "Chief Research Compliance Officer",
        "Research Compliance Director",
        "Research Compliance Manager",
        "Senior Research Compliance Officer",
        "Research Compliance Officer",
        "Head of Research Governance",
        "Research Governance Manager",
        "Head of Research Governance and Compliance",
        "Associate Director of Research Contracts, Compliance and Commercial Research",
        "Trusted Research Manager",
        "Research Security Manager",
        "Export Control Director (Research)",
        "Export Control Manager (Research)",
        "Head of Research Contracts and Research Compliance",
        "Assistant Director, Research Compliance and Grant Administration",
        "Research Integrity Officer",
        "Head of Research Integrity",
        "Research Security and Contracts Manager",
        "Director of Research Security",
        "Compliance and Assurance Manager",
        "Contracts and Compliance Manager",
        "Research Risk and Compliance Manager",
        "Director of Research Integrity and Compliance",
        "Director of the Office of Research Integrity",
        "Executive Director of the Office of Research Integrity",
        "Director for Research Integrity and Infrastructure",
        "Institutional Research Integrity Officer",
        "Research Compliance Analyst",
        "Director of Human Research Protection Program",
        "Human Research Protection Program Director",
        "Director of Human Subjects Office",
        "IRB Director",
        "IRB Coordinator",
        "IRB Administrator",
        "IRB Application Analyst",
        "Reliance Manager",
        "Conflict of Interest in Research Manager",
        "Research Security Officer",
        "Director of Research Security and Export Control",
        "Export Compliance Officer",
        "Chief Export Compliance Officer",
        "Senior Export Compliance Officer",
        "Senior Export Control Compliance Officer",
        "Senior Export Compliance Analyst",
        "Research Security and Facility Security Officer",
        "Grants and Contracts Administrator",
        "Grant and Contract Administrator",
        "Grants and Contracts Specialist",
        "Senior Grants and Contracts Specialist",
        "Grants and Contracts Analyst",
        "Senior Grants and Contracts Analyst",
        "Contract Analyst",
        "Senior Contract Analyst",
    ],
    "Research Finance & Accounting": [
        "Director of Research Finance",
        "Head of Research Finance",
        "Research Finance Director",
        "Senior Research Finance Manager",
        "Research Finance Manager",
        "Assistant Research Finance Manager",
        "Senior Research Finance Partner",
        "Research Finance Partner",
        "Senior Finance Business Partner (Research)",
        "Finance Business Partner (Research)",
        "Research Finance Business Partner",
        "Senior Research Finance Officer",
        "Research Finance Officer",
        "Senior Research Finance Analyst",
        "Research Finance Analyst",
        "Senior Research Accountant",
        "Research Accountant",
        "Director of Grants Accounting",
        "Head of Grants Accounting",
        "Grants Accounting Director",
        "Senior Grants Accounting Manager",
        "Grants Accounting Manager",
        "Senior Grants Accountant",
        "Grants Accountant",
        "Grants Finance Director",
        "Head of Grants Finance",
        "Senior Grants Finance Manager",
        "Grants Finance Manager",
        "Sponsored Research Finance Director",
        "Sponsored Research Finance Manager",
        "Director of Contracts and Grants Accounting",
        "Research Awards Finance Manager",
        "Research Costing Manager",
        "Head of Research Costing",
        "Director, Grants and Capital Projects Accounting",
        "Manager, Grants Accounting",
        "Grants Account Specialist",
        "Grants Analyst",
        "Strategic Finance Partner",
        "Director, Strategic Finance Partners",
        "Contracts and Grants Accounting Manager",
        "Contract and Grant Accounting Manager",
        "Grant Finance Manager",
        "Research Grant Accountant",
        "Research Costings Officer",
        "Director of Grant Accounting",
        "Grants and Financial Manager",
        "Senior Finance and Grants Manager",
        "Grants Finance Specialist",
        "Director of Post-Award Accounting and Reporting",
        "C&G Accounting Director",
        "Sponsored Projects Accountant",
        "Sponsor Project Accountant",
        "Associate Director, Grant and Contract Financial Administration",
        "Senior Financial and Grant Analyst",
        "Financial and Grant Analyst",
        "Grant Accountant",
    ],
    "Sponsored / Grants / Awards": [
        # Pre-Award
        "Pre-Award Director",
        "Director of Pre-Award Services",
        "Head of Pre-Award Services",
        "Head of Pre-Award",
        "Associate Director of Pre-Award",
        "Assistant Director of Pre-Award",
        "Senior Pre-Award Manager",
        "Pre-Award Manager",
        "Pre-Award Grants Manager",
        "Pre-Award Grant Manager",
        "Pre-Award Officer",
        "Pre-Award Administrator",
        "Pre-Award Specialist",
        "Pre-Award Research Administrator",
        "Director, Pre-Award Administration",
        "Associate Director, Pre-Award Administration",
        "Assistant Director, Pre-Award Administration",
        "Senior Manager, Pre-Award Administration",
        "Pre-Award Administration Manager",
        "Pre-Award Grants Administrator",
        "Proposal Manager",
        "Proposal Development Manager",
        "Proposal Project Manager",
        "Proposal Coordinator",
        "PreAward Director",
        "PreAward Manager",
        "Senior Pre-Award Administrator",
        "Senior Pre-Award Grants Specialist",
        "Pre-Award Grants Specialist",
        "Manager, Pre-Award Services",
        "Senior Grants and Contracts Officer",
        "Grants and Contracts Officer",
        "Contract and Grant Officer, Senior",
        "Pre-Award Contracts Administrator",
        # Post-Award
        "Post-Award Director",
        "Director of Post-Award Services",
        "Director, Post-Award Services",
        "Director, Post-Award Administration",
        "Head of Post-Award Services",
        "Head of Post-Award",
        "Associate Director of Post-Award",
        "Assistant Director of Post-Award",
        "Senior Post-Award Manager",
        "Post-Award Manager",
        "Post-Award Grants Manager",
        "Post-Award Officer",
        "Post-Award Administrator",
        "Post-Award Specialist",
        "Post-Award Research Administrator",
        "Post-Award Administration Manager",
        "Post-Award Grants Administrator",
        "Post-Award Grant Accountant",
        "Post-Award Accountant",
        "Award Setup Manager",
        "Award Setup Specialist",
        "Award Closeout Manager",
        "Post Award Assistant Director",
        "Post Award Coordinator",
        "Post Award Administrator",
        "Post Award Analyst",
        "Associate Director of Post-Award Operations",
        "Manager, Post-Award Administration",
        "Senior Manager, Post-Award Research Administration",
        "Manager, Post-Award Research Administration",
        "Grants & Post-Award Coordinator",
        "Post-Award Principal Professional",
        # Sponsored Programs / Grants / Awards
        "Executive Director of Sponsored Programs",
        "Senior Director of Sponsored Programs",
        "Director of Sponsored Programs",
        "Director of Sponsored Programmes",
        "Associate Director of Sponsored Programs",
        "Assistant Director of Sponsored Programs",
        "Head of Sponsored Programs",
        "Head of Sponsored Programmes",
        "Sponsored Programs Director",
        "Sponsored Programmes Director",
        "Executive Director of Sponsored Research",
        "Director of Sponsored Research",
        "Associate Director of Sponsored Research",
        "Head of Sponsored Research",
        "Sponsored Research Director",
        "Director of Research Grants",
        "Head of Research Grants",
        "Research Grants Director",
        "Senior Research Grants Manager",
        "Research Grants Manager",
        "Assistant Research Grants Manager",
        "Senior Research Grants Officer",
        "Research Grants Officer",
        "Research Grants Adviser",
        "Research Grants Specialist",
        "Grants Director",
        "Director of Grants",
        "Head of Grants",
        "Senior Grants Manager",
        "Grants Manager",
        "Senior Grants Officer",
        "Grants Officer",
        "Senior Grants Administrator",
        "Grants Administrator",
        "Director of Research Awards",
        "Head of Research Awards",
        "Research Awards Director",
        "Research Awards Manager",
        "Award Management Manager",
        "Sponsored Programs Specialist",
        "Director of the Office of Sponsored Programs",
        "Sponsored Development Manager",
        "Sponsored Development Specialist",
        "Director of Grant Support",
        "Associate Director of Grants and Foundation Relations",
        "Director, College Grant Support",
        "Proposal and Award Manager",
        "Director of Sponsored Projects",
        "Associate Director of Sponsored Projects",
        "Assistant Director of Sponsored Projects",
        "Sponsored Projects Director",
        "Sponsored Projects Manager",
        "Sponsored Projects Administrator",
        "Sponsored Program Coordinator",
        "Sponsored Programs Associate",
        "Senior Research Administrator",
        "Lead Research Administrator",
        "Research Administrator",
        "Research Administration Manager",
        "Research Administrator Manager",
        "Unit Research Administrator",
        "Senior Unit Research Administrator",
        "Division Research Administrator",
        "Associate Research Administrator",
        "Research Administrator Senior",
        "Subawards Manager",
        "Subaward Specialist",
        "Senior Subaward and Consortium Manager",
        "Chief Grants Management Officer",
        "Deputy Grants Management Officer",
        "Lead Grants Management Officer",
        "Grants Management Officer",
        "Grants Management Specialist",
        "Senior Grants Management Specialist",
        "Grants and Agreements Officer",
        "Grants and Agreements Specialist",
        "Program Official",
        "Program Officer",
        "Scientific Review Officer",
        "NSF Program Director",
        # Research Development and Funding
        "Research Development Director",
        "Director of Research Development",
        "Head of Research Development",
        "Associate Director of Research Development",
        "Deputy Director of Research Development",
        "Senior Research Development Manager",
        "Research Development Manager",
        "Assistant Research Development Manager",
        "Senior Research Development Officer",
        "Research Development Officer",
        "Senior Research Development Adviser",
        "Research Development Adviser",
        "Senior Research Development Specialist",
        "Research Development Specialist",
        "Research Funding Director",
        "Director of Research Funding",
        "Head of Research Funding",
        "Senior Research Funding Manager",
        "Research Funding Manager",
        "Senior Research Funding Officer",
        "Research Funding Officer",
        "Research Funding Adviser",
        "Research Funding and Development Officer",
        "Research Funding and Development Manager",
        "Research Strategy and Development Manager",
        "Research Development and Partnerships Manager",
        "Research Development Digitisation Manager",
        "Director of Research Development and Services",
        "Head of Research Development and Support",
        "Research Development Coordinator",
        "Research Development Facilitator",
        "Senior Research Facilitator",
        "Research Facilitator",
        "Funding Development Manager",
        "Development Officer Research",
        "EU Research Development Manager",
        "Research Development Manager (International)",
        "Head of Research Development (International)",
        "Head of Research Development (Faculty Partnering)",
        "Associate Director of Research Funding",
        "Senior Grant Development Officer",
        "Grant Development Officer",
        "Grants Development Specialist",
        "Grant Proposal Writer",
        "Grant Writer",
        "Grant Program Coordinator",
        "Grant Program Manager",
        "Grants Program Manager",
        "Proposal Development Specialist",
        "Lead Proposal Services Coordinator",
        "Proposal Services Coordinator",
        "Director of Research Program Development and Grants",
        "Research Development Associate",
    ],
    "Research Systems & Digital": [
        "Director of Research Systems",
        "Head of Research Systems",
        "Research Systems Director",
        "Senior Research Systems Manager",
        "Research Systems Manager",
        "Research Systems Officer",
        "Senior Research Systems Analyst",
        "Research Systems Analyst",
        "Director of Research Systems and Information",
        "Head of Research Systems and Information",
        "Research Data and Systems Manager",
        "Research Information Systems Manager",
        "Research Information Manager",
        "Director of Research Information",
        "Head of Research Information",
        "Research Data Director",
        "Head of Research Data",
        "Senior Research Data Manager",
        "Research Data Manager",
        "Research Analytics Director",
        "Head of Research Analytics",
        "Research Analytics Manager",
        "Research Reporting Manager",
        "Research Business Intelligence Manager",
        "Director of Research Digital Transformation",
        "Head of Research Digital Transformation",
        "Research Digital Transformation Manager",
        "Research Administration Systems Manager",
        "Research Grants Systems Manager",
        "Grants Management Systems Manager",
        "Research Portfolio Systems Manager",
        "Director of Business Systems",
        "Head of Business Systems",
        "Business Systems Manager",
        "Director of Finance Systems",
        "Head of Finance Systems",
        "Finance Systems Manager",
        "Director of Digital Transformation",
        "Head of Digital Transformation",
        "Digital Transformation Director",
        "Digital Transformation Manager",
        "Director of IT and Digital Transformation",
        "Director of Digital Transformation and Technology",
        "Director of Enterprise Applications",
        "Team Manager – Research Systems and Information",
        "Head of Research Information Systems",
        "Research Information & Systems Manager",
        "Head of Research Information and Systems",
        "Head of Research Information, Quality and Impact",
        "Head of Research Information & Evaluation",
        "Research Information Officer (Training and Support)",
        "Research Information Officer",
        "Research Administration Reporting Project Manager",
        "Senior Director, Research Systems and Support",
        "Assistant Director for Research Administration Systems",
        "Manager, Research Administration Support",
        "Research Administration Support and Education Specialist",
        "Director of Research Administration Information Systems",
        "Research Administration Analyst",
        "Senior Research Administration Specialist",
        "Research Administration Specialist",
        "eRA Analyst",
        "IRIS Technical Director",
        "Director of Research PMO",
        "Research PMO Director",
        "Associate Vice President for Research Computing",
        "Director of Research Computing",
        "Director of Research Computing Services",
        "Executive Director of Research Computing Technologies",
        "Director of Research Computing and Data",
        "Director of Research IT",
        "Director of Research Cyberinfrastructure",
    ],
    "Secondary": [
        "President & Vice Chancellor",
        "Vice Chancellor",
        "CFO",
        "Finance Director",
        "Director of Finance",
        "Head of Finance",
        "Finance Manager",
        "CIO",
        "CTO",
        "IT Director",
        "Director Digital Transformation",
        "PVC Knowledge Exchange",
        "Director Innovation & Enterprise",
        "Director Knowledge Exchange",
        "Research Office Manager",
        "Senior Contracts Manager",
        "Vice Provost",
        "Associate Vice Provost",
        "Director of Finance & Administration",
        "Assistant Provost for Scholarship and Creative Activity",
    ],
}


def _normalise(title):
    t = str(title or "").lower()
    # Unify hyphens/spaces
    t = t.replace("–", "-").replace("—", "-")
    t = re.sub(r"[\-]+", "-", t)          # collapse dashes
    t = re.sub(r"\s+", " ", t).strip()
    return t


# Pre-compute normalised title -> category mapping, longest first
_ENTRIES = []
for cat in CATEGORY_ORDER:
    for title in SENIOR_TITLES.get(cat, []):
        _ENTRIES.append((_normalise(title), cat))
# Sort longest normalised title first so specific phrases win
_ENTRIES.sort(key=lambda t: -len(t[0]))


def classify_title(title):
    """Return (category, canonical_title_matched) or (None, None)."""
    if not title:
        return None, None
    tn = _normalise(title)
    # Also strip common suffixes that hide behind commas / dashes
    for canon, cat in _ENTRIES:
        # phrase match anywhere in the normalised title
        if canon in tn:
            # find the source Title (case-preserved) that matches canon
            for src in SENIOR_TITLES[cat]:
                if _normalise(src) == canon:
                    return cat, src
            return cat, canon
    return None, None
