"""
Senior title taxonomy (v7 - 556 titles across 10 categories).

Each fine-grained category is folded to ONE of three persona umbrellas
so the app stays aligned with Ian's spec (Research / Finance /
IT-Systems).

Public API
    PERSONA_ORDER            list of three umbrella personas
    SENIOR_TITLES            {fine_category: [titles]} - kept for audit
    CATEGORY_TO_PERSONA      {fine_category: umbrella_persona}
    SECONDARY_OVERRIDES      {title (lower): persona} - for the mixed
                              "Secondary & Review-Only" group
    classify_title(title)    -> (persona | None, canonical_title | None)
    persona_of_title(title)  -> persona | None  (shorthand)

Matching is case-insensitive and longest-title-first. International
titles (DE, FR, ES, IT, PL, JP, KR, CN, IN etc.) are included so
non-English job titles from LinkedIn / CRM extracts get bucketed too.
"""
from __future__ import annotations

import re
from typing import Optional, Tuple


PERSONA_ORDER = ["Research", "Finance", "IT-Systems"]


# =============================================================================
# 10 fine-grained categories from v7
# =============================================================================
SENIOR_TITLES = {
    # ---------------------------------------------------------------- 1
    "Research Leadership, Office & Strategy": [
        "Director of Research", "Head of Research",
        "Director of Research Services",
        "Executive Director of Research Services",
        "Senior Director of Research Services",
        "Head of Research Services",
        "Associate Director of Research Services",
        "Deputy Director of Research Services",
        "Director of Research Support", "Head of Research Support",
        "Director of Research Office", "Head of Research Office",
        "Research Office Director",
        "Director of Research Operations",
        "Head of Research Operations", "Research Operations Director",
        "Director of Research Operations and Services",
        "Director of Research and Innovation",
        "Head of Research and Innovation",
        "Director of Research and Enterprise",
        "Head of Research and Enterprise",
        "Director of Research and Knowledge Exchange",
        "Head of Research and Knowledge Exchange",
        "Director of Research and Innovation Services",
        "Director of Research and Enterprise Services",
        "Director of Research and Knowledge Exchange Services",
        "Head of Research and Innovation Services",
        "Head of Research and Enterprise Services",
        "Head of Research and Knowledge Exchange Services",
        "Director of Research Strategy", "Head of Research Strategy",
        "Research Strategy Director",
        "Director of Research Innovation and Knowledge Exchange",
        "Deputy Director of Research and Enterprise",
        "Executive Director Research and Innovation Services",
        "Director of Research Engagement and Innovation Office",
        "Director of Research Innovation and Impact",
        "Director of Research and Impact",
        "Director of Research and Innovation Office",
        "Director of Research Support and Governance",
        "Head of Research Support and Governance",
        "Director of Office of Research Management",
        "Executive Director of Office of Research Management",
        "Director of Research Administration",
        "Chief Research Administration Officer",
        "Assistant Dean for Research Administration",
        "Associate Dean for Research",
        "Director of Sponsored Projects",
        "Director of the Office of Sponsored Projects",
        "Research Manager", "Faculty Research Manager",
        "Head of Research Policy", "Research Policy Manager",
        "Director, Research Office",
        "Director, Research Services Division",
        "Director, Research Services",
        "Director: Research Office",
        "Director of Research, Innovation and Partnerships",
        "Head of Research Support Office",
        "Head of Grants Office",
        "Leiter Forschungsservice", "Leiterin Forschungsservice",
        "Dezernent Forschung", "Dezernentin Forschung",
        "Directeur de la Recherche et de la Valorisation",
        "Directrice de la Recherche et de la Valorisation",
        "Jefe de Servicio de Gestion de la Investigacion",
        "Jefa de Servicio de Gestion de la Investigacion",
        "Dirigente Area Ricerca", "Responsabile Ufficio Ricerca",
        "Forskningsadministrativ chef",
        "Kierownik Dzialu Nauki",
        "Director of Research Promotion Division",
        "Chief URA", "Senior URA",
        "Director, Industry-Academic Cooperation Foundation",
        "Director of Science and Technology Department",
        "Deputy Director, Office of Scientific Research",
        "Head of Research Cell",
        "Coordinator, Research & Development Cell",
        "Jefe de la Oficina de Gestion de la Investigacion",
        "Jefa de la Oficina de Gestion de la Investigacion",
        "Director General de Investigacion y Posgrado",
        "Directora General de Investigacion y Posgrado",
    ],
    # ---------------------------------------------------------------- 2
    "Senior Research Executives & Global Equivalents": [
        "Pro-Vice-Chancellor (Research)",
        "Pro-Vice-Chancellor (Research and Innovation)",
        "Pro-Vice-Chancellor (Research and Knowledge Exchange)",
        "Pro Vice-Chancellor for Research",
        "Pro Vice-Chancellor for Research and Innovation",
        "Vice-Principal (Research)",
        "Vice-Principal (Research and Innovation)",
        "Vice-Principal (Research and Knowledge Exchange)",
        "Deputy Vice-Chancellor (Research)",
        "Deputy Vice-Chancellor (Research and Innovation)",
        "Deputy Vice-Chancellor (Research and Enterprise)",
        "Vice President for Research",
        "Vice President for Research and Innovation",
        "Vice President for Research and Economic Development",
        "Vice President for Research and Knowledge Transfer",
        "Vice Chancellor for Research",
        "Vice Chancellor for Research and Innovation",
        "Senior Vice Chancellor for Research",
        "Senior Vice Chancellor for Research and Innovation",
        "Vice Provost for Research",
        "Vice Provost for Research and Innovation",
        "Vice Provost for Research and Creative Activity",
        "Associate Vice Provost for Research",
        "Assistant Vice Provost for Research",
        "Assistant Vice President for Research",
        "Associate Vice President for Research",
        "Associate Vice President for Research Development",
        "Interim Vice Provost for Research Development",
        "Vice-Rector for Research",
        "Vice-Rector for Research and Innovation",
        "Vice-Rector of Faculty and Research",
        "Vice-President (Research and Innovation)",
        "Vice-President Research",
        "Vice-President Research and Strategic Initiatives",
        "Senior Vice President (Research and Innovation)",
        "Senior Associate Vice President for Research",
        "Executive Vice President for Research",
        "Deputy President (Research and Technology)",
        "Deputy President (Research and Innovation)",
        "Chief Research Officer",
        "Pro-Warden for Research Enterprise and Knowledge Exchange",
        "Provost and Deputy Vice-Chancellor for Research and Knowledge Exchange",
        "Associate Vice-President (Research)",
        "Pro Vice-Chancellor (Research Performance)",
        "Deputy Vice-Chancellor (Research, Innovation & Outreach)",
        "Dean (Research & Development)",
        "Dean (Sponsored Research & Industrial Consultancy)",
        "Dean IRD",
        "Associate Dean (Sponsored Research)",
        "Dean of Scientific Research",
        "Vice Dean for Scientific Research",
        "Vice Rector for Graduate Studies and Scientific Research",
        "Vice President for Research & Graduate Studies",
        "Chief Research & Innovation Officer",
        "Prorektor Forschung", "Prorektorin Forschung",
        "Vizepraesident Forschung", "Vizepraesidentin Forschung",
        "Vice-President Recherche", "Vice-Presidente Recherche",
        "Vicerrector de Investigacion",
        "Vicerrectora de Investigacion",
        "Vice-Reitor para a Investigacao",
        "Vice-Reitora para a Investigacao",
        "Pro-Reitor de Pesquisa", "Pro-Reitora de Pesquisa",
        "Pro-Reitor de Pesquisa e Pos-Graduacao",
        "Pro-Reitora de Pesquisa e Pos-Graduacao",
        "Prorettore alla Ricerca",
        "Prorektor ds. Nauki",
        "Prorektor pro vedu",
        "Prodekan for forskning",
        "Forskningsdirektor",
        "Secretario de Ciencia y Tecnica",
        "Dean of Research and Development",
    ],
    # ---------------------------------------------------------------- 3
    "Research Development & Funding": [
        "Research Funding Director", "Director of Research Funding",
        "Head of Research Funding",
        "Associate Director of Research Funding",
        "Research Funding Manager", "Senior Research Funding Manager",
        "Research Funding Officer",
        "Senior Research Funding Officer",
        "Research Development Director",
        "Director of Research Development",
        "Head of Research Development",
        "Associate Director of Research Development",
        "Deputy Director of Research Development",
        "Director of Research Development and Services",
        "Head of Research Development and Support",
        "Senior Research Development Manager",
        "Research Development Manager",
        "Assistant Research Development Manager",
        "Research Development Officer",
        "Senior Research Development Officer",
        "Senior Research Development Specialist",
        "Research Development Manager (International)",
        "Head of Research Development (International)",
        "Head of Research Development (Faculty Partnering)",
        "EU Research Development Manager",
        "Research Development Digitisation Manager",
        "Research Funding and Development Manager",
        "Research Funding and Development Officer",
        "Research Strategy and Development Manager",
        "Funding Development Manager",
        "Director of Research Program Development and Grants",
        "Director of Strategic Research Development",
        "Assistant Vice President for Strategic Research Development",
        "Associate Director of Strategic Research Development",
        "Research Development Strategist",
        "Senior Research Development Strategist",
        "Research Facilitator", "Senior Research Facilitator",
        "Grants Facilitator",
        "European Funding Manager",
        "Manager, Research Development",
        "Research Development Coordinator",
        "Postgraduate & Research Funding Officer",
        "Leiter Forschungsfoerderung",
        "Leiterin Forschungsfoerderung",
        "Referent Forschungsfoerderung",
        "Referentin Forschungsfoerderung",
        "Forschungsreferent", "Forschungsreferentin",
        "EU-Referent", "EU-Referentin",
        "Grant Advisor", "Grant Support Officer", "Funding Advisor",
        "Charge de projets europeens",
        "Chargee de projets europeens",
        "Responsable de Proyectos Europeos",
        "Responsabile Ufficio Progetti Europei",
        "Forskningssekreterare", "Forskningsradgivare",
        "EU-koordinator", "Forskningskoordinator",
        "Head of External Funding Section",
        "Kierownik Centrum Obslugi Projektow",
        "Gestor de Ciencia e Tecnologia",
        "Gestora de Ciencia e Tecnologia",
    ],
    # ---------------------------------------------------------------- 4
    "Sponsored Programmes, Grants & Awards": [
        "Director of Research and Sponsored Programs",
        "Senior Director of Research and Sponsored Programs",
        "Director of Research Scholarship and Sponsored Programs",
        "Director of the Office of Research and Sponsored Programs",
        "Assistant Vice President for Sponsored Programs",
        "Assistant Vice President and Director of Sponsored Programs",
        "Associate Director of Sponsored Programs",
        "Assistant Director of Sponsored Programs",
        "Head of Sponsored Programs", "Head of Sponsored Programmes",
        "Sponsored Programs Director",
        "Sponsored Programmes Director",
        "Sponsored Programs Officer", "Senior Sponsored Programs Officer",
        "Sponsored Programs Administrator",
        "Sponsored Programs Manager",
        "Director of Sponsored Research",
        "Head of Sponsored Research", "Sponsored Research Director",
        "Director of Research Grants", "Head of Research Grants",
        "Research Grants Director", "Senior Research Grants Manager",
        "Research Grants Manager",
        "Grants Director", "Director of Grants", "Head of Grants",
        "Senior Grants Manager", "Grants Manager",
        "Senior Grants Officer",
        "Director of Research Awards", "Research Awards Director",
        "Head of Research Awards", "Research Awards Manager",
        "Awards Manager", "Award Management Manager",
        "Director of Grant Support",
        "Chief Grants Management Officer",
        "Lead Grants Management Officer",
        "Grants Management Specialist",
        "Senior Grants Management Specialist",
        "Subaward Manager", "Outgoing Subaward Manager",
        "Subaward Administrator", "Subaward Team Lead",
        "Research Grants Officer",
        "Research Grants Administrator",
        "Research Services Officer",
        "Research Awards Officer",
        "Manager: Research Grants Administration",
        "Research Grants Unit Manager",
        "Manager, Research Services",
        "Head of Research Support Services",
        "Team Leader, Research Support Team",
        "Deputy Registrar (Sponsored Research)",
        "Assistant Registrar (Sponsored Research)",
        "Section Officer (Sponsored Research)",
        "Project Coordinator (SRIC)",
        "Gestionnaire de contrats de recherche",
        "Tecnico de gestion de proyectos",
        "Tecnica de gestion de proyectos",
        "Gestor de Proyectos", "Gestora de Proyectos",
        "Coordinador de Proyectos", "Coordinadora de Proyectos",
        "Gerente de Projetos, Fundacao de Apoio",
        "Projectbeheerder",
        "Head of Awards", "Awards Director", "Award Lead",
        "Head of Grants Management Unit",
        "Sub-grants Manager", "Grants Portfolio Manager",
        "Director of Grants Management",
        "Grants Operations Manager", "Grants Administrator",
        "Senior Program Officer", "Program Officer",
        "Portfolio Manager", "Head of Funding Operations",
        "Funding Operations Manager", "Grants Policy Manager",
    ],
    # ---------------------------------------------------------------- 5
    "Pre-Award": [
        "PreAward Director", "PreAward Manager",
        "Pre-Award Grant Manager",
        "Director of Pre-Award Services",
        "Head of Pre-Award", "Head of Pre-Award Services",
        "Associate Director of Pre-Award",
        "Assistant Director of Pre-Award",
        "Senior Pre-Award Manager",
        "Pre-Award Grants Manager",
        "Pre-Award Officer", "Pre-Award Administrator",
        "Senior Pre-Award Grants Specialist",
        "Pre-Award Grants Specialist",
        "Manager, Pre-Award Services",
        "Proposal Manager", "Proposal Officer",
        "Proposal Development Specialist",
        "Proposal Development Manager",
        "Grants Officer (Pre-Award)",
        "Application & Assessment Manager", "Call Manager",
    ],
    # ---------------------------------------------------------------- 6
    "Post-Award": [
        "Post Award Assistant Director",
        "Post-Award Director",
        "Director of Post-Award Services",
        "Head of Post-Award", "Head of Post-Award Services",
        "Senior Post-Award Manager", "Post-Award Manager",
        "Post-Award Grants Manager",
        "Post-Award Administrator", "Post-Award Specialist",
        "Award Management Specialist", "Award Setup Manager",
        "Grants Officer (Post-Award)", "Post-Award Officer",
        "Award Manager", "Awards Coordinator",
        "Grant Implementation Manager", "Award Monitoring Manager",
    ],
    # ---------------------------------------------------------------- 7
    "Research Contracts, Governance & Compliance": [
        "Contracts and Grants Director",
        "Director of Contracts and Grants",
        "Head of Contracts and Grants",
        "Director of Research Contracts", "Head of Research Contracts",
        "Research Contracts Director",
        "Senior Research Contracts Manager",
        "Research Contracts Manager", "Research Contracts Officer",
        "Grants and Contracts Officer",
        "Senior Grants and Contracts Officer",
        "Contract and Grant Officer, Senior",
        "Grants and Contracts Specialist",
        "Senior Grants and Contracts Specialist",
        "Director of Contracting",
        "Associate Director of Contracting", "Contracting Manager",
        "Contracting Officer", "Senior Contracting Officer",
        "Director of Research Compliance",
        "Head of Research Compliance",
        "Chief Research Compliance Officer",
        "Research Compliance Director",
        "Research Compliance Manager",
        "Senior Research Compliance Officer",
        "Research Compliance Officer",
        "Research Compliance Analyst", "Compliance Analyst",
        "Head of Research Governance",
        "Research Governance Manager",
        "Associate Director of Research Contracts, Compliance and Commercial Research",
        "Head of Research Governance and Compliance",
        "Director of Research Integrity",
        "Senior Director of Research Integrity, Security and Compliance",
        "Research Integrity Officer",
        "Deputy Research Integrity Officer",
        "Deputy Director of Research Integrity and Compliance",
        "Conflict of Interest Manager", "COI Administrator",
        "Research Security Manager", "Export Control Officer",
        "Authorized Organizational Representative",
        "Signing Official", "Institutional Official",
        "Director of Contract Negotiation",
        "Senior Contract Negotiator",
        "Contracts Officer (Research)",
        "Research Finance and Compliance Manager",
        "Research Governance Officer",
        "Research Integrity Advisor",
        "Manager, Research Ethics & Integrity",
        "Grants and Compliance Manager", "Donor Compliance Lead",
        "Restricted Funding Manager", "Grants Compliance Officer",
        "Assurance Manager", "Funding Assurance Manager",
    ],
    # ---------------------------------------------------------------- 8
    "Research Finance & Grants Accounting": [
        "Research Finance Director", "Director of Research Finance",
        "Head of Research Finance",
        "Senior Research Finance Manager", "Research Finance Manager",
        "Senior Research Finance Officer",
        "Grants Finance Director", "Head of Grants Finance",
        "Grants Finance Manager", "Senior Grants Finance Manager",
        "Grants Finance Specialist", "Grant Finance Manager",
        "Research Awards Finance Manager", "Research Costing Manager",
        "Head of Research Costing", "Research Costings Officer",
        "Senior Finance and Grants Manager",
        "Assistant Vice President for Contracts and Grants",
        "Assistant Vice President and Director of Contracts and Grants",
        "Associate Director of Contracts and Grants",
        "Assistant Director of Contracts and Grants",
        "Grants Accounting Manager", "Grants Accounting Supervisor",
        "Grants Accountant", "Senior Grants Accountant",
        "Lead Grants Accountant",
        "Subaward Accountant", "Sponsored Programs Accountant",
        "Sponsored Research Accountant", "Post-Award Accountant",
        "Letter of Credit Accountant",
        "Letter of Credit Draws Accountant",
        "Director of Finance, Research Foundation",
        "Assistant Director of Accounting, Research Foundation",
        "Research Foundation Accountant",
        "Research Foundation Controller",
        "Director of Sponsored Projects Accounting",
        "Sponsored Projects Accounting Manager",
        "Assistant Controller - Grants and Contracts",
        "Controller - Sponsored Programs",
        "Director of Post-Award Financial Management",
        "Director of Cost Analysis",
        "Director of Effort Reporting", "Effort Reporting Manager",
        "Director of Clinical Research Finance",
        "Clinical Research Finance Manager",
        "Subrecipient Monitoring Manager", "Sponsored Billing Manager",
        "Research Accounts Manager", "Head of Research Accounts",
        "Research Accountant",
        "Deputy Director (Research Finance)",
        "TRAC Manager",
        "Manager, Research Finance",
        "Research Finance Analyst",
        "Manager, Research Accounting",
        "Deputy Director: Research Finance",
        "Deputy Bursar (Research)", "Finance Manager (Grants)",
        "Grants and Contracts Manager",
        "Research Finance Section Head",
        "Deputy Finance Officer",
        "Leiter Drittmittelverwaltung",
        "Leiterin Drittmittelverwaltung",
        "Sachgebietsleiter Drittmittel",
        "Sachgebietsleiterin Drittmittel",
        "Projectcontroller", "Controller Onderzoek",
        "Responsable du pole financier recherche",
        "Responsable administratif et financier",
        "Coordenador Financeiro, Fundacao de Apoio",
        "Coordenadora Financeira, Fundacao de Apoio",
        "Partnerships Finance Manager",
        "Grants Finance Coordinator", "Program Finance Officer",
    ],
    # ---------------------------------------------------------------- 9
    "Research Systems, Data, Digital & Research IT": [
        "Director of Research Systems", "Head of Research Systems",
        "Research Systems Director", "Senior Research Systems Manager",
        "Research Systems Manager", "Research Systems Officer",
        "Research Systems Analyst", "Senior Research Systems Analyst",
        "Director of Research Systems and Information",
        "Head of Research Systems and Information",
        "Team Manager - Research Systems and Information",
        "Senior Director, Research Systems and Support",
        "Research Data and Systems Manager",
        "Research Information Systems Manager",
        "Head of Research Information Systems",
        "Head of Research Information and Systems",
        "Head of Research Information, Quality and Impact",
        "Research Information Manager",
        "Director of Research Information",
        "Head of Research Information",
        "Director of Information Services (Office of Research)",
        "Associate Director of Information Services (Office of Research)",
        "Research Administration Systems Business Analyst",
        "Business Analyst (Research Information Services)",
        "Data Management Analyst (Research Systems)",
        "Application Developer Analyst (Research Systems)",
        "Application Database Administrator (Research Systems)",
        "Research Data Director", "Head of Research Data",
        "Research Data Manager", "Senior Research Data Manager",
        "Research Analytics Director", "Head of Research Analytics",
        "Research Analytics Manager", "Research Reporting Manager",
        "Research Business Intelligence Manager",
        "Director of Research Digital Transformation",
        "Head of Research Digital Transformation",
        "Research Digital Transformation Manager",
        "Research Grants Systems Manager",
        "Grants Management Systems Manager",
        "Research Portfolio Systems Manager",
        "Director of Business Systems", "Head of Business Systems",
        "Business Systems Manager",
        "Director of Finance Systems", "Head of Finance Systems",
        "Finance Systems Manager",
        "Director of Digital Transformation",
        "Head of Digital Transformation",
        "Digital Transformation Director",
        "Digital Transformation Manager",
        "Director of IT and Digital Transformation",
        "Director of Digital Transformation and Technology",
        "Director of Enterprise Applications",
        "eRA Analyst", "IRIS Technical Director",
        "Director of Research PMO", "Research PMO Director",
        "Associate Vice President for Research Computing",
        "Director of Research Computing",
        "Director of Research Computing Services",
        "Executive Director of Research Computing Technologies",
        "Director of Research Computing and Data",
        "Director of Research IT",
        "REF Manager", "Research Information Officer",
        "Manager, Research Performance & Analytics",
        "Research Systems Coordinator",
        "Research Information Systems Analyst",
    ],
    # ---------------------------------------------------------------- 10
    "Secondary & Review-Only": [
        "Vice Chancellor", "President & Vice Chancellor",
        "CFO", "Finance Director", "Director of Finance",
        "Head of Finance", "Finance Manager",
        "CIO", "CTO", "IT Director",
        "Director Digital Transformation",
        "PVC Knowledge Exchange",
        "Director Innovation & Enterprise",
        "Director Knowledge Exchange",
        "Research Office Manager", "Senior Contracts Manager",
        "Vice Provost", "Associate Vice Provost",
        "Assistant Provost for Scholarship and Creative Activity",
        "Kanzler", "Kanzlerin",
        "Directeur des Affaires Financieres",
        "Directrice des Affaires Financieres",
        "Directeur General des Services",
        "Directrice Generale des Services",
        "Direttore Generale", "Gerente",
        "Bursar", "Registrar",
        "Finance Officer",
        "Controller of Finance & Accounts",
        "Chief Finance & Accounts Officer",
        "Country Director", "Chief Program Officer",
    ],
}


# =============================================================================
# Categories -> the three umbrella personas
# =============================================================================
CATEGORY_TO_PERSONA = {
    "Research Leadership, Office & Strategy":        "Research",
    "Senior Research Executives & Global Equivalents": "Research",
    "Research Development & Funding":                "Research",
    "Sponsored Programmes, Grants & Awards":         "Research",
    "Pre-Award":                                     "Research",
    "Post-Award":                                    "Research",
    "Research Contracts, Governance & Compliance":   "Research",
    "Research Finance & Grants Accounting":          "Finance",
    "Research Systems, Data, Digital & Research IT": "IT-Systems",
    # Secondary is mixed - handled by SECONDARY_OVERRIDES below.
    "Secondary & Review-Only":                       None,
}


# Explicit persona per secondary-title (rest default to Research when
# no override is set).
SECONDARY_OVERRIDES = {
    # Finance-flavoured
    "cfo":                                              "Finance",
    "finance director":                                 "Finance",
    "director of finance":                              "Finance",
    "head of finance":                                  "Finance",
    "finance manager":                                  "Finance",
    "kanzler":                                          "Finance",
    "kanzlerin":                                        "Finance",
    "directeur des affaires financieres":               "Finance",
    "directrice des affaires financieres":              "Finance",
    "directeur general des services":                   "Finance",
    "directrice generale des services":                 "Finance",
    "direttore generale":                               "Finance",
    "gerente":                                          "Finance",
    "bursar":                                           "Finance",
    "finance officer":                                  "Finance",
    "controller of finance & accounts":                 "Finance",
    "chief finance & accounts officer":                 "Finance",
    # IT-flavoured
    "cio":                                              "IT-Systems",
    "cto":                                              "IT-Systems",
    "it director":                                      "IT-Systems",
    "director digital transformation":                  "IT-Systems",
    # Research-flavoured (top exec / research office)
    "vice chancellor":                                  "Research",
    "president & vice chancellor":                      "Research",
    "pvc knowledge exchange":                           "Research",
    "director innovation & enterprise":                 "Research",
    "director knowledge exchange":                      "Research",
    "research office manager":                          "Research",
    "senior contracts manager":                         "Research",
    "vice provost":                                     "Research",
    "associate vice provost":                           "Research",
    "assistant provost for scholarship and creative activity": "Research",
    "registrar":                                        "Research",
    "country director":                                 "Research",
    "chief program officer":                            "Research",
}


# =============================================================================
# Matching
# =============================================================================
def _normalise(title: str) -> str:
    """Lowercase, collapse dashes & whitespace so 'Pre-Award Manager'
    and 'pre - award manager' both match a canonical 'pre-award manager'.
    We keep diacritics stripped by the caller (senior_titles keeps
    ASCII forms) so tolerant matching works on either input."""
    t = str(title or "").lower()
    t = t.replace("–", "-").replace("—", "-")
    t = re.sub(r"[\-\s]+", " ", t).strip()
    return t


# Flat, longest-first list of (normalised_canonical, category, persona)
_ENTRIES: list[Tuple[str, str, str]] = []
for _cat, _titles in SENIOR_TITLES.items():
    _base_persona = CATEGORY_TO_PERSONA.get(_cat)
    for _t in _titles:
        _n = _normalise(_t)
        if _cat == "Secondary & Review-Only":
            _p = SECONDARY_OVERRIDES.get(_n, "Research")
        else:
            _p = _base_persona
        _ENTRIES.append((_n, _cat, _p))
# Longest first so more-specific phrases win
_ENTRIES.sort(key=lambda t: -len(t[0]))


def classify_title(title: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Return (umbrella_persona, canonical_title) for the FIRST matching
    entry, or (None, None) if nothing matched. Umbrella persona is
    one of PERSONA_ORDER.
    """
    if not title:
        return None, None
    tn = _normalise(title)
    for canon_n, _cat, persona in _ENTRIES:
        if canon_n and canon_n in tn:
            return persona, canon_n
    return None, None


def persona_of_title(title: str) -> Optional[str]:
    """Shorthand - return only the umbrella persona (or None)."""
    return classify_title(title)[0]
